-- MySQL Script generated by MySQL Workbench
-- Wed Feb 15 14:10:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`passenger` ;

CREATE TABLE IF NOT EXISTS `mydb`.`passenger` (
  `id` INT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `birth_date` VARCHAR(45) NULL,
  `mobile_phone` VARCHAR(45) NULL,
  `passport_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NULL,
  `password` VARCHAR(255) NULL,
  `role` VARCHAR(45) NULL,
  `enabled` TINYINT(1) NOT NULL,
  `passenger_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `passenger_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`passenger` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`station` ;

CREATE TABLE IF NOT EXISTS `mydb`.`station` (
  `id` INT NULL,
  `name` VARCHAR(45) NULL,
  `stop_duration` TIME NULL,
  `closed` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`route_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`route_part` ;

CREATE TABLE IF NOT EXISTS `mydb`.`route_part` (
  `id` INT NULL,
  `station_id_from` INT NOT NULL,
  `station_id_to` INT NULL,
  `price` DOUBLE NULL,
  `time_passing` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `station_id_from_idx` (`station_id_from` ASC) VISIBLE,
  CONSTRAINT `time_passing`
    FOREIGN KEY ()
    REFERENCES `mydb`.`station` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `station_id_from`
    FOREIGN KEY (`station_id_from`)
    REFERENCES `mydb`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`route` ;

CREATE TABLE IF NOT EXISTS `mydb`.`route` (
  `id` INT NULL,
  `route_part_id_start` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `route_part_id_start_idx` (`route_part_id_start` ASC) VISIBLE,
  CONSTRAINT `route_part_id_start`
    FOREIGN KEY (`route_part_id_start`)
    REFERENCES `mydb`.`route_part` (`station_id_from`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`train` ;

CREATE TABLE IF NOT EXISTS `mydb`.`train` (
  `id` INT NULL,
  `number` VARCHAR(45) NULL,
  `departure_time` DATETIME NULL,
  `count_of_seats` INT NULL,
  `cancelled` TINYINT NULL,
  `route_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `route_id_idx` (`route_id` ASC) VISIBLE,
  CONSTRAINT `route_id`
    FOREIGN KEY (`route_id`)
    REFERENCES `mydb`.`route` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NULL,
  `passenger_id` INT NOT NULL,
  `train_id` INT NULL,
  `departure_date` DATETIME NULL,
  `cost` DECIMAL NOT NULL,
  `station_id_departure` INT NULL,
  `station_id_destination` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `passenger_id_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `train_id_idx` (`train_id` ASC) VISIBLE,
  INDEX `station_id_departure_idx` (`station_id_departure` ASC) VISIBLE,
  INDEX `station_id_destination_idx` (`station_id_destination` ASC) VISIBLE,
  CONSTRAINT `passenger_id`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `mydb`.`passenger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `train_id`
    FOREIGN KEY (`train_id`)
    REFERENCES `mydb`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `station_id_departure`
    FOREIGN KEY (`station_id_departure`)
    REFERENCES `mydb`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `station_id_destination`
    FOREIGN KEY (`station_id_destination`)
    REFERENCES `mydb`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`confirmation_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`confirmation_token` ;

CREATE TABLE IF NOT EXISTS `mydb`.`confirmation_token` (
  `id` INT NULL,
  `token` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `expires_at` TIMESTAMP NULL,
  `confirmed_at` TIMESTAMP NULL,
  `user_id` INT NULL,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_ticket` (
  `id` INT NULL,
  `user_id` INT NOT NULL,
  `ticket_id` INT NULL,
  `payment_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `ticket_id_idx` (`ticket_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ticket_id`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`route_connection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`route_connection` ;

CREATE TABLE IF NOT EXISTS `mydb`.`route_connection` (
  `id` INT NULL,
  `route_part_id` INT NULL,
  `route_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `route_id_idx` (`route_part_id` ASC, `route_id` ASC) VISIBLE,
  CONSTRAINT `route_part_id`
    FOREIGN KEY (`route_part_id`)
    REFERENCES `mydb`.`route_part` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `route_id`
    FOREIGN KEY (`route_part_id` , `route_id`)
    REFERENCES `mydb`.`route` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
