spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/railways_db
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hbm2ddl:
          auto: update
        spring:
